### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by devarshishimpi** [GrowInCommunity/support#15]
### Name

Devarshi Shimpi

### Discord Username (if applicable)

lil.dev#0383

**Comment by devarshishimpi** [comment]
@Akshaykumar05

**Comment by ni5arga** [comment]
Invites are automated actually, invitations are sent as soon as you open an issue but you need to close the issue by yourself.

**Comment by devarshishimpi** [comment]
> Invites are automated actually, invitations are sent as soon as you open an issue but you need to close the issue by yourself.

I know. @Akshaykumar05 invited me via email, so I didn't need this anymore, therefore closed the issue 🙂 And yes, the issue gets closed automatically too, it doesn't need a manual close.

**Comment by ni5arga** [comment]
I tried last night several times, there's some problem, the issues are not
getting closed and the comment is not coming up but invites are going out.

**Comment by devarshishimpi** [comment]
Seems like some issue with the invite-member github action, will check out

**Comment by ni5arga** [comment]
thanks
