### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by SaarthakMaini** [GrowInCommunity/support#18]
### Name

Saarthak Maini

### Discord Username (if applicable)

SaarthakMaini#9597

**Comment by priyankarpal** [comment]
Click on organization & join the org & also close the issue after joining

![image](https://github.com/GrowInCommunity/support/assets/88102392/f1268310-9842-469c-acd4-7e148f5066bc)

**Comment by SaarthakMaini** [comment]
I have joined the organization. Thank you very much!
