### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by paharipratyush** [GrowInCommunity/support#25]
### Name

PRATYUSH PAHARI

### Discord Username (if applicable)

PRATYUSH#2894

### Additional Context

I got to know about it from the twitter handle of GrowIn Community and I would like to join in the GitHub Community Organization 🤗

**Comment by priyankarpal** [comment]
Click on `Your Organization` & accept the invitation. also, feel free to close this issue. after joining the ORG

![image](https://github.com/GrowInCommunity/support/assets/88102392/b0312513-0b66-44d3-9498-2254a7966a6d)
