### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by vaibhav1mahajan** [GrowInCommunity/support#28]
### Name

Vaibhav Mahajan

### Discord Username (if applicable)

Vaibhav#2359

**Comment by priyankarpal** [comment]
Click on `Your Organization` & accept the invitation. also, feel free to close this issue. after joining the ORG

![image](https://github.com/GrowInCommunity/support/assets/88102392/b0312513-0b66-44d3-9498-2254a7966a6d)
