### ISSUE TITLE
The invitation.yml workflow isn't working.

### ISSUE THREAD

**Issue by sahil-sagwekar2652** [GrowInCommunity/support#36]
#### I've checked the logs of the workflow runs and they're showing this error - 
![image](https://github.com/GrowInCommunity/support/assets/89456541/c5c8ff01-1a31-464b-90fb-4f6c0014a698)

#### To my knowledge, I think the error might be caused to the permissions for the INVITE_TOKEN being setup incorrectly, do check if it has the following permissions -  
![image](https://github.com/GrowInCommunity/support/assets/89456541/10324f06-8851-4ea8-b1f9-f50bf21bc892)

**Comment by ni5arga** [comment]
The invite token is set up correctly afaik, the invitation token isn't set up on my account. I'll check.

**Comment by ni5arga** [comment]
https://github.com/GrowInCommunity/support/issues/44
