### ISSUE TITLE
fix action settings

### ISSUE THREAD

**Issue by priyazsh** [GrowInCommunity/support#44]
To fix the auto close issue not working

- Go to https://github.com/GrowInCommunity/support/settings/actions
- Scroll down to **Workflow permissions**
- Select "Read and write permissions" and tick on "Allow GitHub actions to create and approve pull requests" 

![image](https://github.com/GrowInCommunity/support/assets/83062406/fd5757f6-c21f-464f-938b-a09b74ec9a8b)

**Comment by ni5arga** [comment]
I don't have access to the org settings, I have only access to the repo settings and can't do this because I think the workflow thing is disabled from org settings, @Akshaykumar05 please take a look.

**Comment by ni5arga** [comment]
I'm unable to check that, I can confirm I have access to the settings but I'm unable to click on the radio button, I get a red cross sign

**Comment by ni5arga** [comment]
@Akshaykumar05 Please go to https://github.com/organizations/growincommunity/settings/actions and check on Read and Write permissions and then go to https://github.com/GrowInCommunity/support/settings/actions and Select "Read and write permissions" and tick on "Allow GitHub actions to create and approve pull requests"

**Comment by ni5arga** [comment]
![image](https://github.com/GrowInCommunity/support/assets/45588772/8c6b924a-3293-4c1b-9d7f-083ca0539228)
Fixed

**Comment by ni5arga** [comment]
Thanks for the help!

**Comment by Akshaykumar05** [comment]
Welcome @ni5arga
